### ISSUE TITLE
Organization on commitlint config is changed

### ISSUE THREAD

**Issue by jrmclaurin** [jedwards1211/0-60#6]
When using a skeleton that has this fragment in package.json:

`"commitlint": {
    "extends": [
      "@jcoreio/commitlint-config"
    ]
  },`

If I'm making a package for @anotherOrg, the fragment above, and the `devDependencies` entry, are changed from `@jcoreio/commitlint-config` to `@anotherOrg/commitlint-config`.

**Comment by jedwards1211** [comment]
yep, I need to fix this, I was hoping to be able to always replace the org with another, but it doesn't always work

**Comment by jedwards1211** [comment]
fixed in a61a254d64e540cc74b9166e7ca3c71a0a431f62
